"""Addad cart price

Revision ID: 6af9afa6801b
Revises: 7f44d10ba198
Create Date: 2025-04-20 02:02:59.042367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6af9afa6801b'
down_revision = '7f44d10ba198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_reference', sa.String(length=255), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('transaction_reference')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('paystack_reference')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
