"""modified payment method and status

Revision ID: 9da0f4498f4b
Revises: c8067aa9e29f
Create Date: 2025-04-20 16:56:32.291107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da0f4498f4b'
down_revision = 'c8067aa9e29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentMethod', sa.Enum('Paystack', 'Mobilemoney'), nullable=False))
        batch_op.add_column(sa.Column('paymentStatus', sa.Enum('Pending', 'Success'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('paymentStatus')
        batch_op.drop_column('paymentMethod')

    # ### end Alembic commands ###
