"""ProductID

Revision ID: b14df0fdbb3b
Revises: 6af9afa6801b
Create Date: 2025-04-20 02:33:56.938375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b14df0fdbb3b'
down_revision = '6af9afa6801b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productID', sa.Integer(), nullable=False))
        batch_op.drop_constraint('cart_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['productID'], ['productsID'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_ibfk_2', 'product', ['product_id'], ['productsID'])
        batch_op.drop_column('productID')

    # ### end Alembic commands ###
