"""Add order_status column to orders

Revision ID: c8067aa9e29f
Revises: b14df0fdbb3b
Create Date: 2025-04-20 12:35:56.355046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8067aa9e29f'
down_revision = 'b14df0fdbb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_status', sa.Enum('Unpaid', 'Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_status')

    # ### end Alembic commands ###
